use_frameworks!

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'A_Example' do
  pod 'A', :path => '../'

  target 'A_Tests' do
    inherit! :search_paths

    
  end
end
